In [2]:
import torch

In [5]:
randint = torch.randint(-5, 5, (9,))
randint

tensor([ 0, -4, -3, -2, -4, -4, -4, -1, -1])

In [9]:
tensor_ = torch.tensor([[2, 3], [4,9], [2.3, 0.89]])
tensor_

tensor([[2.0000, 3.0000],
        [4.0000, 9.0000],
        [2.3000, 0.8900]])

In [11]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
empty = torch.empty((3, 4), dtype = torch.int64)
empty

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [24]:
arange = torch.arange(9)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
linspace = torch.linspace(-50, 50, 11)
linspace

tensor([-50., -40., -30., -20., -10.,   0.,  10.,  20.,  30.,  40.,  50.])

In [29]:
logspace = torch.logspace(-50, 50, 11)
logspace

tensor([0.0000e+00, 9.9999e-41, 1.0000e-30, 1.0000e-20, 1.0000e-10, 1.0000e+00,
        1.0000e+10, 1.0000e+20, 1.0000e+30,        inf,        inf])

In [35]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [39]:
a = torch.empty(3, 5, dtype = torch.float64)
empty_like = torch.empty_like(a)
empty_like

tensor([[3.0402e-311,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],
       dtype=torch.float64)