In [1]:
import numpy as np
import torch
import time 
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [2]:
#region: Time block
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()
#endregion

elapsed_time = end_time - start_time
print(f"{elapsed_time:.32f}")

0.00146675109863281250000000000000


In [3]:
a, b, c, d = 100, 100, 100, 100
torch_rand1 = torch.rand(a, b, c, d).to(device)
torch_rand2 = torch.rand(a, b, c, d).to(device)
np_rand1 = torch.rand(a, b, c, d).numpy()
np_rand2 = torch.rand(a, b, c, d).numpy()

start_time = time.time()
rand = torch_rand1 @ torch_rand2
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Torch(cuda) elapsed time: {elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2) # rand = np_rand1 * np_rand2
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Numpy(cpu) elapsed time: {elapsed_time:.8f}")

Torch(cuda) elapsed time: 0.41575122
Numpy(cpu) elapsed time: 0.49065828


In [4]:
t0 = time.time()
tensors =  torch.ones(100,100) #must NOT use 10**5 -> too big
t1 = time.time()
delta = t1 - t0
print(delta)

0.0007395744323730469


In [5]:
#torch.multinomial
probabilities = torch.tensor([0.3, 0.7]) #30% of 0 and 70% of 1
a = torch.empty(10, 10)
for i in range(10):
    a[i] = torch.multinomial(probabilities, num_samples = 10, replacement = True) 
    print(a[i])

tensor([1., 0., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 1., 0., 1., 1., 0., 1., 1., 0., 1.])
tensor([1., 0., 0., 1., 0., 1., 1., 1., 1., 1.])
tensor([1., 0., 1., 0., 1., 0., 1., 1., 1., 0.])
tensor([0., 1., 1., 1., 1., 1., 0., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 0., 1., 1.])
tensor([1., 1., 1., 1., 0., 1., 1., 1., 1., 1.])
tensor([1., 0., 1., 1., 0., 0., 1., 0., 0., 0.])
tensor([1., 1., 0., 1., 1., 0., 1., 0., 0., 1.])
tensor([1., 1., 1., 1., 1., 1., 0., 1., 1., 1.])


In [6]:
#Concatenate 2-tensors
tensor1 = torch.tensor([[2., 3.], [5., 2.]])
tensor2 = torch.ones(2, 2)
my_tensor = torch.cat((tensor1, tensor2), dim = 1)
my_tensor.type
my_tensor

tensor([[2., 3., 1., 1.],
        [5., 2., 1., 1.]])

In [7]:
#Concatenate 3-tensors
tensor1 = torch.ones(3, 3, 3)
tensor2 = torch.tensor([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]] ])
my_tensor = torch.cat((tensor1, tensor2), dim = 2)
my_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 2.],
         [1., 1., 1., 3.]],

        [[1., 1., 1., 4.],
         [1., 1., 1., 5.],
         [1., 1., 1., 6.]],

        [[1., 1., 1., 7.],
         [1., 1., 1., 8.],
         [1., 1., 1., 9.]]])