In [1]:
import numpy as np
import torch
import time 
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [2]:
#region: Time block
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()
#endregion

elapsed_time = end_time - start_time
print(f"{elapsed_time:.32f}")

0.00146675109863281250000000000000


In [3]:
a, b, c, d = 100, 100, 100, 100
torch_rand1 = torch.rand(a, b, c, d).to(device)
torch_rand2 = torch.rand(a, b, c, d).to(device)
np_rand1 = torch.rand(a, b, c, d).numpy()
np_rand2 = torch.rand(a, b, c, d).numpy()

start_time = time.time()
rand = torch_rand1 @ torch_rand2
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Torch(cuda) elapsed time: {elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2) # rand = np_rand1 * np_rand2
end_time = time.time()

elapsed_time = end_time - start_time
print(f"Numpy(cpu) elapsed time: {elapsed_time:.8f}")

Torch(cuda) elapsed time: 0.41575122
Numpy(cpu) elapsed time: 0.49065828


In [4]:
t0 = time.time()
tensors =  torch.ones(100,100) #must NOT use 10**5 -> too big
t1 = time.time()
delta = t1 - t0
print(delta)

0.0007395744323730469


In [5]:
#torch.multinomial
probabilities = torch.tensor([0.3, 0.7]) #30% of 0 and 70% of 1
a = torch.empty(10, 10)
for i in range(10):
    a[i] = torch.multinomial(probabilities, num_samples = 10, replacement = True) 
    print(a[i])

tensor([1., 0., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 1., 0., 1., 1., 0., 1., 1., 0., 1.])
tensor([1., 0., 0., 1., 0., 1., 1., 1., 1., 1.])
tensor([1., 0., 1., 0., 1., 0., 1., 1., 1., 0.])
tensor([0., 1., 1., 1., 1., 1., 0., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 0., 1., 1.])
tensor([1., 1., 1., 1., 0., 1., 1., 1., 1., 1.])
tensor([1., 0., 1., 1., 0., 0., 1., 0., 0., 0.])
tensor([1., 1., 0., 1., 1., 0., 1., 0., 0., 1.])
tensor([1., 1., 1., 1., 1., 1., 0., 1., 1., 1.])


In [6]:
#Concatenate 2-tensors
tensor1 = torch.tensor([[2., 3.], [5., 2.]])
tensor2 = torch.ones(2, 2)
my_tensor = torch.cat((tensor1, tensor2), dim = 1)
my_tensor.type
my_tensor

tensor([[2., 3., 1., 1.],
        [5., 2., 1., 1.]])

In [7]:
#Concatenate 3-tensors
tensor1 = torch.ones(3, 3, 3)
tensor2 = torch.tensor([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]] ])
my_tensor = torch.cat((tensor1, tensor2), dim = 2)
my_tensor

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 2.],
         [1., 1., 1., 3.]],

        [[1., 1., 1., 4.],
         [1., 1., 1., 5.],
         [1., 1., 1., 6.]],

        [[1., 1., 1., 7.],
         [1., 1., 1., 8.],
         [1., 1., 1., 9.]]])

In [22]:
#Triangle-lower and triangle-upper
tensor = torch.ones(5, 5)
tensor
print(torch.tril(tensor), "\n\n", torch.triu(tensor) )

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]]) 

 tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [35]:
#Masked fill (mask, value)
tensor = torch.zeros(5, 5)
res = tensor.masked_fill(torch.triu(torch.ones(5, 5))==0, float('-inf'))
print(res, '\n')
#Exponential
print(torch.exp(res)) #exp of 0 is 1 and of -inf is 0

tensor([[0., 0., 0., 0., 0.],
        [-inf, 0., 0., 0., 0.],
        [-inf, -inf, 0., 0., 0.],
        [-inf, -inf, -inf, 0., 0.],
        [-inf, -inf, -inf, -inf, 0.]]) 

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [58]:
#Transpose
tens = torch.tensor([[1, 2, 3], [4, 5, 6]])
tens
print(tens)
print(torch.transpose(tens, 0, 1), '\n')

ztens = torch.zeros(2, 3, 4)
ztens = ztens.transpose(0, 2)
ztens.shape

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]]) 



torch.Size([4, 3, 2])

In [64]:
#Stack
tensor1 = torch.ones(3)
tensor2 = torch.zeros(3)
tensor3 = torch.tensor([1, 4, 7])
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1., 1., 1.],
        [0., 0., 0.],
        [1., 4., 7.]])

In [74]:
#Linear
import torch.nn as nn
_input = torch.tensor([10., 10., 10.])
linear_output = nn.Linear(3, 3, bias=False)
print(linear_output(_input))

tensor([ 4.5368, -2.3376,  4.9748], grad_fn=<SqueezeBackward4>)


In [67]:
#Softmax
import torch.nn.functional as F
_input = torch.tensor([1., 2., 3.])
output = F.softmax(_input, dim=0)
print(output)

tensor([0.0900, 0.2447, 0.6652])


In [76]:
#Embedding vectors
# Suppose you have 10 words in your vocabulary, each will be mapped to a 5D vector
embedding = nn.Embedding(num_embeddings=10, embedding_dim=5)

# Input: batch of word indices (e.g., sentence: [2, 5, 0])
word_ids = torch.tensor([2, 5, 0])

# Get embeddings
word_vectors = embedding(word_ids)
print(word_vectors.shape)  # torch.Size([3, 5])


torch.Size([3, 5])
